version: '3.8'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: gcs-db
      MYSQL_USER: user
      MYSQL_PASSWORD: db_password
    ports:
      - "13306:3306"
    volumes:
      - db_data:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  backend:
    build:
      context: .
      dockerfile: dockerfile-backend
    volumes:
      - .:/home/node/backend
    ports:
      - "8080:8080"
    restart: always
    environment:
      DB_NAME: gcs-db
      DB_USER: user
      DB_PASSWORD: db_password
      DB_HOST: db
      DB_PORT: 3306
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      RABBITMQ_PORT: 5672
      NODE_ENV: production
    depends_on:
      - db
      - rabbitmq
volumes:
  db_data: