version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    ports:
      - "8080:8080"
    command: npm run backend
    user: node
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge